name: bump-casks

on:
  schedule:
    - cron:  '0 8,20 * * *'
  workflow_dispatch:

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        token: ${{secrets.GH_TOKEN}}
        tap: viarotel-org/escrcpy
        cask: escrcpy
        livecheck: true
        dryrun: true